object Version {
    const val coreKtxVersion = "1.10.1"
    const val appcompatVersion = "1.6.1"
    const val materialVersion = "1.9.0"
    const val constraintlayoutVersion = "2.1.4"
    const val junitVersion = "4.13.2"
    const val testJunitVersion = "1.1.5"
    const val espressoVersion = "3.5.1"
    const val retrofitVersion = "2.9.0"
    const val daggerHiltVersion = "2.47"
    const val loggingInterceptorVersion = "4.9.1"
    const val roomVersion = "2.5.2"
    const val kotlinCoroutinesVersion = "1.3.9"
    const val pagingVersion = "3.1.1"
    const val lifecycleVersion = "2.6.1"
    const val activityKtxVersion = "1.7.2"
    const val turbineVersion = "0.11.0"
    const val mockitoVersion = "3.12.4"
    const val archCoreTestingVersion = "2.2.0"
    const val coroutinesTestVersion = "1.6.1"
    const val testCoreKtx = "1.5.0"
    const val glideVersion = "4.16.0"
}